// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zcbyxfaqaehzsoestrtk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpjYnl4ZmFxYWVoenNvZXN0cnRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0NjI2MzMsImV4cCI6MjA2MTAzODYzM30.DB32VoDMYPrSc7rP_J9O65Y4Zd-pxPv-J0nA5FotZMQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);